config/routes.rb
Rails.application.routes.draw do
  resources :depenses
  resources :categories
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'depenses#new', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get 'account/edit', to: 'account#edit', as: 'edit_account'
  patch 'account', to: 'account#update'
  get 'account', to: 'account#edit' # Optional: Redirect the main account page to the edit action
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/depense.rb
class Depense < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :monthly_debit_date, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 28 }
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_action :authenticate_user! # Ensure the user is logged in

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to account_path, notice: 'Vous avez mis à jour votre date de début du mois avec succès.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:monthly_debit_date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :user_authorized?, only: %i[show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user: current_user).order(:name)
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    Depense.where(category: @category).destroy_all
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :user_id)
    end

    def user_authorized?
      if @category.user_id != current_user.id
        redirect_to categories_path, notice: "Vous n'êtes pas autorisé à accéder à cette page"
      end
    end
end

app/controllers/depenses_controller.rb
class DepensesController < ApplicationController
  before_action :set_depense, only: %i[ show edit update destroy ]
  before_action :user_authorized?, only: %i[show edit update destroy ]

  # GET /depenses or /depenses.json
  def index
    if params[:start_date].present? && params[:end_date].present?
      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])
      @depenses = Depense.where(user: current_user).where(date: start_date..end_date)
    else
      current_date = Date.current
      if current_date.day < current_user.monthly_debit_date
        # Display expenses from the previous month
        starting_date = (current_date.beginning_of_month - 1.month) + (current_user.monthly_debit_date - 1).days
      else
        # Display expenses from the current month
        starting_date = current_date.beginning_of_month + (current_user.monthly_debit_date - 1).days
      end

      @depenses = Depense.where(user: current_user).where("date >= ?", starting_date)
    end
  end

  # GET /depenses/1 or /depenses/1.json
  def show
  end

  # GET /depenses/new
  def new
    if Category.where(user: current_user).empty?
      redirect_to depenses_path, alert: "Vous devez d'abord créer au moins une catégorie"
    end
    @depense = Depense.new
  end

  # GET /depenses/1/edit
  def edit
  end

  # POST /depenses or /depenses.json
  def create
    @depense = Depense.new(depense_params)

    respond_to do |format|
      if @depense.save
        format.html { redirect_to depense_url(@depense), notice: "Depense was successfully created." }
        format.json { render :show, status: :created, location: @depense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @depense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /depenses/1 or /depenses/1.json
  def update
    respond_to do |format|
      if @depense.update(depense_params)
        format.html { redirect_to depense_url(@depense), notice: "Depense was successfully updated." }
        format.json { render :show, status: :ok, location: @depense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @depense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depenses/1 or /depenses/1.json
  def destroy
    @depense.destroy

    respond_to do |format|
      format.html { redirect_to depenses_url, notice: "Depense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_depense
      @depense = Depense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def depense_params
      params.require(:depense).permit(:date, :user_id, :category_id, :amount)
    end

    def user_authorized?
      if @depense.user != current_user
        redirect_to depenses_path, notice: "Vous n'êtes pas autorisé à voir cette page"
      end
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/depenses_helper.rb
module DepensesHelper
end

app/views/categories/_form.html.erb
<%= bootstrap_form_for(@category) do |form| %>
  <div class="field">
    <%= form.text_field :name, label: "Nom" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Valider" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1> Modifier la catégorie</h1>

<%= render 'form', category: @category %>

<%= link_to 'Voir la catégorie', @category %> |
<%= link_to 'Voir les catégories', categories_path %>

app/views/categories/index.html.erb
<h1>Catégories</h1>

<div class="container">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @categories.where(user: current_user).each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Voir', category, class: "btn btn-secondary btn-sm" %></td>
        <td><%= link_to 'Modifier', edit_category_path(category), class: "btn btn-primary btn-sm" %></td>
        <td>
          <%= link_to 'Supprimer',
                      category,
                      method: :delete,
                      data: { confirm: "Attention, si vous supprimez cette catégorie, les #{Depense.where(category: category).count} dépenses qui y sont liées seront aussi supprimées" },
                      class: "btn btn-danger btn-sm",
                      title: "Supprimer" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div id="container" style="width:100%; height:400px;"></div>


  <%= link_to 'Nouvelle catégorie', new_category_path, class: "btn btn-primary" %>
</div>

<style>
    .container {
        margin-top: 30px;
    }
</style>
<script>
    if (document.readyState !== 'loading') {
        console.log('document is already ready, just execute code here');
        createChart();
    } else {
        document.addEventListener('DOMContentLoaded', function () {
            console.log('document was not ready, place code here');
            createChart();
        });
    }


    function createChart() {
        Highcharts.chart('container', {
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: 'Répartition des dépenses selon les catégories',
                align: 'center'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            accessibility: {
                point: {
                    valueSuffix: '%'
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
            series: [
                {
                    name: 'Brands',
                    colorByPoint: true,
                    data: [
                        <% @categories.each do |category| %>
                        {
                            name: '<%= category.name %>',
                            y: <%= Depense.where(category: category).sum(:amount) %>
                        },
                        <% end %>
                    ]
                }
            ]
        });
    }
</script>

app/views/categories/new.html.erb
<h1>Nouvelle catégorie</h1>

<%= render 'form', category: @category %>

<%= link_to 'Voir les catégories', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Nom:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Modifier la catégorie', edit_category_path(@category) %> |
<%= link_to 'Voir les catégories', categories_path %>

app/views/depenses/_form.html.erb
<%= bootstrap_form_for(@depense) do |form| %>
  <div class="field">
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.collection_select :category_id, Category.where(user: current_user), :id, :name, label: "Catégorie"%>
  </div>

  <div class="field">
    <%= form.text_field :amount, label: "Montant (€)" %>
  </div>

  <div class="actions">
    <%= form.submit "Valider" %>
  </div>
<% end %>

app/views/depenses/edit.html.erb
<h1>Modifier cette dépense</h1>

<%= render 'form', depense: @depense %>

<%= link_to 'Voir la dépense', @depense %> |
<%= link_to 'Voir les dépenses', depenses_path %>

app/views/depenses/index.html.erb
<h1>Dépenses</h1>

<div class="container">
  <%= bootstrap_form_with url: depenses_path, method: :get, class: "filter-form" do |form| %>
    <div class="form-group row">
      <%= form.label :start_date, "Je préférerais voir les dépenses du", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4">
        <%= form.date_field :start_date, value: params[:start_date], class: "form-control" %>
      </div>
      <%= form.label :end_date, "au", class: "col-sm-2 col-form-label" %>
      <div class="col-sm-4">
        <%= form.date_field :end_date, value: params[:end_date], class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-12 text-center">
        <%= form.submit "Filtrer les dépenses", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Date</th>
      <th>Catégorie</th>
      <th>Montant</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @depenses.where(user: current_user).order(:date).each do |depense| %>
      <tr>
        <td><%= depense.date %></td>
        <td><%= depense.category.name %></td>
        <td><%= depense.amount %>€</td>
        <td><%= link_to 'Voir', depense, class: "btn btn-secondary btn-sm" %></td>
        <td><%= link_to 'Modifier', edit_depense_path(depense), class: "btn btn-primary btn-sm" %></td>
        <td>
          <%= link_to 'Supprimer',
                      depense,
                      method: :delete,
                      data: { confirm: 'Êtes-vous sûr ?' },
                      class: "btn btn-danger btn-sm",
                      title: "Supprimer" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>
  <div id="container" style="width:100%; height:400px;"></div>
</div>
<script>
    if (document.readyState !== 'loading') {
        console.log('document is already ready, just execute code here');
        createChart();
    } else {
        document.addEventListener('DOMContentLoaded', function () {
            console.log('document was not ready, place code here');
            createChart();
        });
    }

    function createChart() {
        Highcharts.chart('container', {
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: 'Répartition des dépenses selon les catégories',
                align: 'center'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            accessibility: {
                point: {
                    valueSuffix: '%'
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
            series: [
                {
                    name: 'Brands',
                    colorByPoint: true,
                    data: [
                        <% Category.where(user: current_user).each do |category| %>
                            {
                                name: '<%= category.name %>',
                                y: <%= Depense.where(category: category).sum(:amount) %>
                            },
                        <% end %>
                    ]
                }
            ]
        });
    }
</script>

  <%= link_to 'Nouvelle dépense', new_depense_path, class: "btn btn-primary" %>
</div>

<style>
    .filter-form {
        margin-bottom: 30px;
    }
</style>

app/views/depenses/new.html.erb
<h1>Nouvelle dépense </h1>

<%= render 'form', depense: @depense %>

<%= link_to 'Voir les dépenses', depenses_path %>

app/views/depenses/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @depense.date %>
</p>

<p>
  <strong>Catégorie:</strong>
  <%= @depense.category.name %>
</p>

<p>
  <strong>Montant:</strong>
  <%= @depense.amount %>€
</p>

<%= link_to 'Modifier la dépense', edit_depense_path(@depense) %> |
<%= link_to 'Voir les dépenses', depenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DepenseManager</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <style>
      /* Add your default styles here */
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background-color: #f1f8ff; /* Light blue color */
      }

      header {
          background-color: #EEEEEE;
          border: #FFFFFF;
          padding: 20px;
      }

      .navbar-brand {
          font-size: 24px;
          font-weight: bold;
          color: #333;
          text-decoration: none;
      }

      .navbar-brand:hover {
          color: #000;
      }

      .navbar-nav .btn {
          margin-left: 10px;
      }

      .notice {
          background-color: #d4edda;
          color: #155724;
          padding: 10px;
          margin-bottom: 20px;
      }

      .alert {
          background-color: #f8d7da;
          color: #721c24;
          padding: 10px;
          margin-bottom: 20px;
      }

      .content-container {
          margin: 0 auto;
          max-width: 800px; /* Adjust the maximum width as needed */
          padding: 20px;
      }
  </style>
</head>

<body>
<header>
  <nav class="navbar navbar-dark">
    <a class="navbar-brand" href="/">Tools</a>
    <a class="btn btn-outline-primary" href="/depenses" role="button">Gérer ses dépenses</a>
    <a class="btn btn-outline-primary" href="/categories" role="button">Gérer ses catégories</a>
    <a class="btn btn-outline-primary" href="/users/edit" role="button">Gérer ses informations de connexion</a>
    <a class="btn btn-outline-primary" href=<%= edit_account_path %> role="button">Gérer ses paramètres</a>
    <form class="form-inline">
      <% if current_user %>
        <a class="btn btn-outline-primary" href="/users/sign_out" role="button">Se déconnecter</a>
      <% else %>
        <a class="btn btn-outline-primary" href="/users/sign_in" role="button">Se connecter</a>
        <a class="btn btn-outline-primary" href="/users/sign_up" role="button">S'inscrire</a>
      <% end %>
    </form>
  </nav>
</header>
<% if notice.present? %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert"><%= alert %></p>
<% end %>
<div class="content-container">
  <%= yield %>
</div>
</body>
</html>